# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy rest of the files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not necessary for stdio-based MCP)

CMD ["node", "build/index.js"]
